### PR TITLE
Created a new file for Code Of Conduct in Japanese Issue No.#148

### PR DESCRIPTION
**Pull request by aliya-rahmani**
References #148  
*Please link to the related issue, using the [references] keyword only if the PR completes the entire issue*
https://github.com/WWCodeTokyo/speak-her-db/issues/148
**Proposed Changes**
Translated the whole text in Japanese
*Description of changes in this PR*
English to Japanese translation

*How do the reviewers QA this? Feel free to write unit tests or describe manual testing steps here*

Added another file for Code Of Conduct in Japanese

### CODE REVIEW

**Comment by tuttiq** [comment]
Thanks @aliya-rahmani ! A few extra requests :

- Please rename the file to `CODE_OF_CONDUCT-JA.md`
- Add a sentence at the top like `For the English version click here` (with a link to the English version)
- Link the Github issue on the PR description
- Are you fluent in Japanese? Do you have any specific concerns about the translation that reviewers should check?

**Review by ann-kilzer — CHANGES_REQUESTED** [review]
Thanks again for your submission. Was this done in Google Translate? What is your Japanese language level?

Please see my comments on the original PR: https://github.com/WWCodeTokyo/speak-her-db/pull/164/files

**Comment by ann-kilzer** [comment]
Hi, we're still waiting on answers to our prior questions. Just to nip this in the bud, if this was merely run through Google Translate and you're not fluent in Japanese, we're going to reject this PR. Users can already use Google Translate's browser plugin to solve that issue, and so we want this document to be translated by a human to convey the important nuances of community guidelines. Thanks for your understanding.

**Comment by aliya-rahmani** [comment]
I'm not that fluent in Japanese so you can do as per your requirements.

**Pull request closed without merging**
