### PR TITLE
2020 > 2022

### PR DESCRIPTION
**Pull request by Shisa-9**
Update-year

**Proposed Changes**
Updating 2020 year to 2022

### CODE REVIEW

**Review by ann-kilzer — COMMENTED** [review]
Hi Ashley, thanks for identifying this issue. This is just the open source license file, so please make the updates to `en.json` and `ja.json` under `/web/src/i18n/locales`

(i18n is short for internationalization in case you didn't know)

**Comment by Shisa-9** [comment]
> Hi Ashley, thanks for identifying this issue. This is just the open source license file, so please make the updates to `en.json` and `ja.json` under `/web/src/i18n/locales`
> 
> (i18n is short for internationalization in case you didn't know)

Thanks so much! I really appreciate the explanation as I had no idea what i18n meant haha

**Review by ann-kilzer — COMMENTED** [review]
I made the date a range. Thanks for finding this!

**Review by Ania-chan — APPROVED** [review]
LGTM

**Pull request merged**
