### PR TITLE
Reduce asset file sizes

### PR DESCRIPTION
**Pull request by BenjaminPrice**
References #106 

**Proposed Changes**

Reduce the file size of the png files while maintaining size and quality.

background.png
793.56 KB -> 107.08 KB(-86%)

banner.png
318.6 KB -> 42.68 KB(-86%)

banner_ja.png
339.43 KB -> 44.04 KB(-87%)

**Testing Plan**

This will need to be tested with a visual check

### CODE REVIEW

**Comment by ann-kilzer** [comment]
Looks pretty good from my end, on a Mac 15" screen. Anyone with a larger monitor want to take a quick pass and look for any 凹凸 unevenness?

**Comment by dominikeinkemmer** [comment]
Checked on my 27" 2k monitor and you definitely notice the quality change quite a bit :/

This PRs changes:
image

Currently deployed version:

**Comment by BenjaminPrice** [comment]
If I get really close to my screen (34" 2K), I can see it. But only then.
Checking it on the deploy preview site: https://deploy-preview-158--speak-her-db.netlify.app/

**Comment by dominikeinkemmer** [comment]
checked again from my macbook connected to the same screen and also my 27" 4k screen, still same result as I posted above (checked through your link this time @BenjaminPrice)

**Comment by BenjaminPrice** [comment]
I'll see if I can take a different approach then.

@ann-kilzer do you have the original source for this image? A PSD or AI file perhaps?

**Comment by BenjaminPrice** [comment]
@ann-kilzer @dominikeinkemmer Using the SVG based on the source now. Should be much better. And, it's only 4kb :)

**Review by ann-kilzer — COMMENTED** [review]
The new image looks great on a macbook. Can someone with a big monitor take a look?

Also, banner.png is for Twitter and OpenGraph cards, so let's not delete it. I am unsure what banner_ja.png is for... @tuttiq do you remember?

**Comment by BenjaminPrice** [comment]
I didn't actually delete the banner files. They're just also shrunk down a bit (github doesn't make that the most clear)

**Comment by ann-kilzer** [comment]
Goodness, I am misreading the red. Sorry about that!

**Comment by tuttiq** [comment]
Tried on my 31.5" WQHD monitor and the image quality seems basically the same of what's deployed in production right now 👍  The colors are slightly lighter tho? lol

Production:
Screen Shot 2020-10-05 at 9 45 35 PM

This PR:
Screen Shot 2020-10-05 at 9 45 50 PM

**Comment by ann-kilzer** [comment]
Let's get it in and I can update the SVG later if I am really missing those blues. Quite strange, there's an transparent blue layer over the whole thing and it clearly presents differently in SVG vs. PNG.

**Review by ann-kilzer — APPROVED** [review]
LGTM 🍍

**Pull request merged**
