### PR TITLE
241 no more email relay

### LINKED ISSUE #241: Remove email relay
Manually forwarding emails is time consuming and brittle.

As there are fewer volunteers on the project, let's switch to something more sustainable.

1. Ensure all speakers have a social media contact point (emails will remain private)
    a. update the form to require one SNS
    b. reach out to speakers who have no SNS information to ask for it

2. Replace the contact form with instructions to reach out to the speaker directly.

3. Disable the Zapier integration

### PR DESCRIPTION
**Pull request by ann-kilzer**
Resolves #241 

Farewell Email Relay

**Proposed Changes**
- remove email relay
- add a message to instruct users on how to contact speakers
- enhance the color of the Social Media icons so users can easily find contact info
- lower the color of the email button because it's just legacy

**Testing Plan**

Look at the list of speakers. Click on the ✉️ icon and check the message. Ensure that clicking OK closes the dialog.

SpeakHer
SpeakHer

### CODE REVIEW

**Comment by Ania-chan** [comment]
@ann-kilzer I run the repo locally but I noticed all the social media links are garbled and are redirecting to non existing links like http://eexiwzj.nphzdoi.de/

**Comment by ann-kilzer** [comment]
@Ania-chan It's probably because you're using the test database?

**Comment by ann-kilzer** [comment]
The deploy preview should give accurate links because it connects to the real DB, not test: https://deploy-preview-264--speak-her-db.netlify.app/

**Review by Ania-chan — APPROVED** [review]
LGTM!!

**Comment by Ania-chan** [comment]
@ann-kilzer Thanks! I can see everything working and I don't have any issue with the code :)

**Pull request merged**
